version: '3.8'

services:

  web:
    container_name: web
    build: ./eMenu
    command: gunicorn eMenu.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - media:/usr/src/app/media/
      - static:/usr/src/app/static/

  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    container_name: celery-worker
    build: ./eMenu
    command: celery -A eMenu worker -l info
    env_file:
      - ./.env
    depends_on:
      - rabbitmq

  celery-beat:
    container_name: celery-beat
    build: ./eMenu
    command: celery -A eMenu beat -l info
    env_file:
      - ./.env
    depends_on:
      - rabbitmq

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - media:/usr/src/app/media/
      - static:/usr/src/app/static/
    depends_on:
      - web

volumes:
  postgres_data:
  media:
  static: